const departmentMagazine = [
  {
    id: 1,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "December 21, 2022",
    image: "/quanta'22.png",
    pdf: "/pdf/Quanta22.pdf",
  },
  //   {
  //     id: 2,
  //     title: "QUANTA'23",
  //     description: "Department Magazine of 2023 edition",
  //     date: "July 15, 2024",
  //     image: "/activity2.png",
  //     pdf: "/pdf/sample-pdf-2.pdf",
  //   },
  //   {
  //     id: 3,
  //     title: "QUANTA'23",
  //     description: "Department Magazine of 2023 edition",
  //     date: "July 15, 2024",
  //     image: "/activity2.png",
  //     pdf: "/pdf/sample-pdf-1.pdf",
  //   },
  //   {
  //     id: 4,
  //     title: "QUANTA'23",
  //     description: "Department Magazine of 2023 edition",
  //     date: "July 15, 2024",
  //     image: "/activity2.png",
  //     pdf: "/pdf/sample-pdf-2.pdf",
  //   },
  //   {
  //     id: 5,
  //     title: "QUANTA'23",
  //     description: "Department Magazine of 2023 edition",
  //     date: "July 15, 2024",
  //     image: "/activity2.png",
  //     pdf: "/pdf/sample-pdf-1.pdf",
  //   },
  //   {
  //     id: 6,
  //     title: "QUANTA'23",
  //     description: "Department Magazine of 2023 edition",
  //     date: "July 15, 2024",
  //     image: "/activity2.png",
  //     pdf: "/pdf/sample-pdf-2.pdf",
  //   },
  //   {
  //     id: 7,
  //     title: "QUANTA'23",
  //     description: "Department Magazine of 2023 edition",
  //     date: "July 15, 2024",
  //     image: "/activity2.png",
  //     pdf: "/pdf/sample-pdf-1.pdf",
  //   },
  //   {
  //     id: 8,
  //     title: "QUANTA'23",
  //     description: "Department Magazine of 2023 edition",
  //     date: "July 15, 2024",
  //     image: "/activity2.png",
  //     pdf: "/pdf/sample-pdf-2.pdf",
  //   },
  //   {
  //     id: 9,
  //     title: "QUANTA'23",
  //     description: "Department Magazine of 2023 edition",
  //     date: "July 15, 2024",
  //     image: "/activity2.png",
  //     pdf: "/pdf/sample-pdf-1.pdf",
  //   },
  //   {
  //     id: 10,
  //     title: "QUANTA'23",
  //     description: "Department Magazine of 2023 edition",
  //     date: "July 15, 2024",
  //     image: "/activity2.png",
  //     pdf: "/pdf/sample-pdf-2.pdf",
  //   },
];
const pgMagazine = [
  {
    id: 1,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-1.pdf",
  },
  {
    id: 2,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-2.pdf",
  },
  {
    id: 3,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-1.pdf",
  },
  {
    id: 4,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-2.pdf",
  },
  {
    id: 5,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-1.pdf",
  },
  {
    id: 6,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-2.pdf",
  },
  {
    id: 7,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-1.pdf",
  },
  {
    id: 8,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-2.pdf",
  },
];
const pgNewsLetter = [
  {
    id: 1,
    title: "CLEAR Magazine September 2021",
    description:
      "Computational Linguistics in Engineering And Research Journal is an initiative of M.Tech Computer Science and Engineering, GEC Sreekrishnapuram",
    image: "/SIMPLE_logo.png",
    date: "Sepetember, 2021",
    pdf: "https://simplegec.blogspot.com/2022/01/clear-magazine-september-2021_13.html?m=0",
  },
];
export { departmentMagazine, pgMagazine, pgNewsLetter };
