const departmentMagazine = [
  {
    id: 1,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-1.pdf",
  },
  {
    id: 2,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-2.pdf",
  },
  {
    id: 3,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-1.pdf",
  },
  {
    id: 4,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-2.pdf",
  },
  {
    id: 5,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-1.pdf",
  },
  {
    id: 6,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-2.pdf",
  },
  {
    id: 7,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-1.pdf",
  },
  {
    id: 8,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-2.pdf",
  },
  {
    id: 9,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-1.pdf",
  },
  {
    id: 10,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-2.pdf",
  },
];
const pgMagazine = [
  {
    id: 1,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-1.pdf",
  },
  {
    id: 2,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-2.pdf",
  },
  {
    id: 3,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-1.pdf",
  },
  {
    id: 4,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-2.pdf",
  },
  {
    id: 5,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-1.pdf",
  },
  {
    id: 6,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-2.pdf",
  },
  {
    id: 7,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-1.pdf",
  },
  {
    id: 8,
    title: "QUANTA'23",
    description: "Department Magazine of 2023 edition",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-2.pdf",
  },
];
const pgNewsLetter = [
  {
    id: 1,
    title: "CLEAR JOURNAL",
    description:
      "Computational Linguistics in Engineering And Research Journal is an initiative of M.Tech Computer Science and Engineering, GEC Sreekrishnapuram",
    date: "July 15, 2024",
    image: "/activity2.png",
    pdf: "/pdf/sample-pdf-1.pdf",
  },
];
export { departmentMagazine, pgMagazine, pgNewsLetter };
